version: '3'

services:
  identityserverbasic:
    image: identityserverbasic
    build:
      context: ./IdentityServerBasic
      dockerfile: Dockerfile
  api1:
    image: api1
    build:
      context: ./Api1
      dockerfile: Dockerfile
