version: '3'

services:
  api1:
    image: api1
    build:
      context: ./Api1
      dockerfile: Dockerfile
services:
  mvcclient:
    image: mvcclient
    build:
      context: ./MvcClient
      dockerfile: Dockerfile

  identityserveridentity:
    image: identityserver
    build:
      context: ./IdentityServerWithAspNetIdentity
      dockerfile: Dockerfile
