version: '3'

services:
  identityserverbasic:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"
  api1:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"
  api1:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"
networks:
  default:
    external:
      name: nat
services:
  mvcclient:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

  identityserveridentity:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"
